apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .OperatorName }}-operator-subscription
  namespace: {{ .InstallNamespace }}
spec:
{{- if .Channel }}
  channel: {{ .Channel }}
{{- end}}
  installPlanApproval: {{ .InstallPlanApproval }} Automatic
  name: {{ .OperatorName }}
  source: {{ .CatalogSource }}
  sourceNamespace: {{ .CatalogSourceNamespace }}
{{- if .StartingCSV }}
  startingCSV: {{ .StartingCSV }}
{{- end}}
