name: cron-update-volsync-helmcharts

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: {} # Useful for testing, but not necessary

jobs:
  update-volsync-helmcharts:
    name: update-volsync-helmcharts
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branches:
          #
          # ACM 2.17 = VolSync 0.16
          # NOTES: - ACM br main is ffwding to release-2.17 atm
          - ACM_BRANCH: "main"
            VOLSYNC_BRANCH: "release-0.16" # VolSync release branch
            ACM_VOLSYNC_HELMCHARTS_DIR: "stable-0.16" # this name matches the operator channel name
          #
          # ACM 2.16 = VolSync 0.15
          - ACM_BRANCH: "release-2.16"
            VOLSYNC_BRANCH: "release-0.15" # VolSync release branch
            ACM_VOLSYNC_HELMCHARTS_DIR: "stable-0.15" # this name matches the operator channel name
          #
          # ACM 2.15 = VolSync 0.14
          - ACM_BRANCH: "release-2.15"
            VOLSYNC_BRANCH: "release-0.14" # VolSync release branch
            ACM_VOLSYNC_HELMCHARTS_DIR: "stable-0.14" # this name matches the operator channel name
          #
          # ACM 2.14 = VolSync 0.13
          - ACM_BRANCH: "release-2.14"
            VOLSYNC_BRANCH: "release-0.13" # VolSync release branch
            ACM_VOLSYNC_HELMCHARTS_DIR: "stable-0.13" # this name matches the operator channel name
          #
          # ACM 2.13 = VolSync 0.12
          - ACM_BRANCH: "release-2.13"
            VOLSYNC_BRANCH: "release-0.12" # VolSync release branch
            ACM_VOLSYNC_HELMCHARTS_DIR: "stable-0.12" # this name matches the operator channel name
    env:
      ACM_BRANCH: ${{ matrix.branches.ACM_BRANCH }}
      VOLSYNC_BRANCH: ${{ matrix.branches.VOLSYNC_BRANCH }}
      ACM_VOLSYNC_HELMCHARTS_DIR: ${{ matrix.branches.ACM_VOLSYNC_HELMCHARTS_DIR }}
    steps:
      - name: "checkout volsync-addon-controller code"
        uses: actions/checkout@v4
        with:
          ref: "${{ env.ACM_BRANCH }}"
          path: "volsync-addon-controller"

      - name: "checkout volsync code (helm charts only)"
        uses: actions/checkout@v4
        with:
          repository: "backube/volsync"
          ref: "${{ env.VOLSYNC_BRANCH }}"
          path: "volsync"
          sparse-checkout: |
            helm

      - name: Update helm charts
        run: |
          mkdir -p $GITHUB_WORKSPACE/volsync-addon-controller/helmcharts/${{ env.ACM_VOLSYNC_HELMCHARTS_DIR }}
          cp -r $GITHUB_WORKSPACE/volsync/helm/volsync $GITHUB_WORKSPACE/volsync-addon-controller/helmcharts/${{ env.ACM_VOLSYNC_HELMCHARTS_DIR }}/
          cd $GITHUB_WORKSPACE/volsync-addon-controller
          git diff helmcharts

      - name: Create Pull Request if helm charts updated
        uses: peter-evans/create-pull-request@v7
        with:
          path: "volsync-addon-controller"
          add-paths: |
            helmcharts/*
          branch: "autoupdate-volsync-helmcharts-${{ env.ACM_BRANCH }}"
          commit-message: "automatic update in ${{ env.ACM_BRANCH }} of VolSync ${{ env.VOLSYNC_BRANCH }} helm charts"
          signoff: true
          sign-commits: true
          title: "[${{ env.ACM_BRANCH }}] Update VolSync ${{ env.VOLSYNC_BRANCH }} helm charts"
          body: |
            Automated update:
              - VolSync helm charts updated for ${{ env.VOLSYNC_BRANCH }} in dir helmcharts/${{ env.ACM_VOLSYNC_HELMCHARTS_DIR }}
          assignees: tesshuflower
          reviewers: tesshuflower
          draft: false
          maintainer-can-modify: true
